wandb_version: 1

device:
  desc: null
  value: cuda:0
notes:
  desc: null
  value: cpu
task:
  desc: null
  value: detection
statement:
  desc: null
  value: 11/4 train model with no denoise queries
train:
  desc: null
  value:
    save_dir: runs/exp1
    epoch: 2
    base_lr: 0.001
    img_size: 800
    label_smoothing: 0.0
    optimizer: null
    save: true
    save_period: 50
    tolerance: 1.0e-05
optimizer:
  desc: null
  value:
    adam:
      lr: 0.001
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
      weight_decay: 0
      amsgrad: false
data:
  desc: null
  value:
    num_classes: 80
    remap_mscoco_category: true
    train_dataloader:
      type: DataLoader
      dataset:
        type: CocoDetection
        img_folder: /data/lcliu/coco_dataset/train2017/
        ann_file: /data/lcliu/coco_dataset/annotations/instances_train2017.json
        transforms:
          type: Compose
          ops: null
      shuffle: true
      batch_size: 8
      num_workers: 4
      drop_last: true
    val_dataloader:
      type: DataLoader
      dataset:
        type: CocoDetection
        img_folder: /data/lcliu/coco_dataset/val2017/
        ann_file: /data/lcliu/coco_dataset/instances_val2017.json
        transforms:
          type: Compose
          ops: null
      shuffle: false
      batch_size: 8
      num_workers: 4
      drop_last: false
model:
  desc: null
  value:
    backbone:
      backbone: resnet50
      weight: null
      dilation: null
      norm_layer: false
    hybirdencoder:
      in_channels:
      - 512
      - 1024
      - 2048
      feat_strides:
      - 8
      - 16
      - 32
      hidden_dim: 256
      nhead: 8
      dim_feedforward: 256
      dropout: 0.0
      enc_act: gelu
      use_encoder_idx:
      - 2
      num_encoder_layers: 1
      pe_temperature: 10000
      expansion: 1.0
      depth_mult: 1.0
      act: silu
      eval_size: null
    RTDETRTransformer:
      num_classes: 80
      hidden_dim: 256
      num_queries: 100
      position_embed_type: sine
      feat_channels:
      - 256
      - 256
      - 256
      feat_strides:
      - 8
      - 16
      - 32
      num_levels: 3
      num_decoder_points: 4
      nhead: 8
      num_decoder_layers: 6
      dim_feedforward: 1024
      dropout: 0.0
      activation: silu
      num_denoising: 0
      label_noise_ratio: 0.5
      box_noise_scale: 1.0
      learnt_init_query: false
      eval_spatial_size: null
      eval_idx: -1
      eps: 0.01
      aux_loss: true
LOSS:
  desc: null
  value:
    SetCriterion:
      weight_dict:
        loss_vfl: 1
        loss_bbox: 5
        loss_giou: 2
      losses:
      - vfl
      - boxes
      eos_coef: 0.0001
      alpha: 0.75
      gamma: 2.0
    matcher:
      type: HungarianMatcher
      weight_dict:
        cost_class: 2
        cost_bbox: 5
        cost_giou: 2
      alpha: 0.25
      gamma: 2.0
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699295019.832723
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.15.10
      8:
      - 5
