task: detection

num_classes: 7
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data/lcliu/neudet_coco/train/
    ann_file: /data/lcliu/neudet_coco/train_annotations.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 2
  num_workers: 1
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data/lcliu/neudet_coco/valid/
    ann_file: /data/lcliu/neudet_coco/valid_annotations.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 2
  num_workers: 1
  drop_last: False